name: Python CI

on:
  pull_request:
  push:
    branches:
      - main
      - feature/setup

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      USE_MOCK: 'true'
      DEMO_SECRET: ${{ secrets.DEMO_SECRET }}

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check Python Syntax
      run: |
        python -m py_compile main.py

    - name: Basic Test
      run: |
        python -c "import main; print('Test import successful')"

    - name: Run app in mock mode
      if: github.ref == 'refs/heads/main'
      run: |
        python main.py